'use client'
import { useEffect } from 'react'
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import { AlertTriangle, CheckCircle2, CloudRain, Gauge, ShieldAlert, X } from 'lucide-react'
import { featureImportance, history, mines, riskClass, type MineId } from '@/lib/rocksense'

function Focus({ mine }: { mine: typeof mines[number] }) { const map = useMap(); useEffect(() => { map.flyTo([mine.lat, mine.lng], 7, { duration: .7 }) }, [mine, map]); return null }
export default function RocksenseMap({ selectedMine, onSelect }: { selectedMine: MineId; onSelect: (id: MineId) => void }) {
  const selected = mines.find(m => m.id === selectedMine) ?? mines[0]
  return <section className="map-page"><div className="map-copy"><p className="eyebrow">GEOSPATIAL VIEW / LIVE-STYLE TELEMETRY</p><h2>Know where the ground is moving.</h2><p>Four synthetic mine sites plotted across the Eastern Coalfields and Singrauli basin. Select a marker to inspect the current stability posture.</p><div className="map-legend"><span><i className="legend-dot low" />LOW</span><span><i className="legend-dot mid" />INTERMEDIATE</span><span><i className="legend-dot high" />HIGH</span></div></div><div className="map-stage"><MapContainer center={[24.0, 84.9]} zoom={6} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{mines.map(m => <CircleMarker key={m.id} center={[m.lat, m.lng]} radius={m.id === selectedMine ? 15 : 10} pathOptions={{ color: m.prediction.risk === 'HIGH' ? '#d95745' : m.prediction.risk === 'INTERMEDIATE' ? '#c47717' : '#4c9b70', fillOpacity: .88, weight: 3 }} eventHandlers={{ click: () => onSelect(m.id) }}><Popup><strong>{m.name}</strong><br />FoS {m.prediction.factorOfSafety} · {m.prediction.risk}</Popup></CircleMarker>)}<Focus mine={selected} /></MapContainer><aside className="mine-panel"><button className="panel-close" aria-label="Close detail panel"><X /></button><p className="eyebrow">SELECTED SITE / {selected.id}</p><h3>{selected.name}</h3><div className="mine-status"><span className={`status-orb ${riskClass(selected.prediction.risk)}`} /><div><strong>{selected.prediction.risk} RISK</strong><small>Updated 02m ago</small></div></div><div className="mine-metrics"><div><span>FoS</span><strong>{selected.prediction.factorOfSafety}</strong></div><div><span>Risk score</span><strong>{selected.prediction.riskScore}<small>/100</small></strong></div><div><span>Rainfall</span><strong>{selected.parameters.rainfall}<small> mm</small></strong></div></div><div className="mine-alerts"><span className="section-label">CURRENT SIGNALS</span>{selected.alerts.slice(0, 2).map((alert, index) => <div className="mine-alert" key={alert}><span className={index === 0 ? 'alert-icon danger' : 'alert-icon'}>{index === 0 ? <ShieldAlert /> : <AlertTriangle />}</span><p>{alert}</p></div>)}</div><div className="mine-actions"><div><Gauge /><span>Model confidence<strong>94%</strong></span></div><div><CloudRain /><span>72h rainfall<strong>{selected.parameters.rainfall} mm</strong></span></div></div></aside></div></section>
}
